--  Generate SQL
--  Version:                   	V7R5M0 220415
--  Generated on:              	06/14/24 14:11:52
--  Relational Database:       	TSDDSSRC
--  Standards Option:          	Db2 for i

CREATE OR REPLACE TABLE DDSCINFO.CUSTOMERS (
CUSTOMER_ID FOR COLUMN CUSTO00001 INTEGER GENERATED ALWAYS AS IDENTITY (
START WITH 1 INCREMENT BY 1
NO MINVALUE NO MAXVALUE
NO CYCLE NO ORDER
CACHE 20 )
,
FIRST_NAME VARCHAR(50) CCSID 937 DEFAULT NULL ,
LAST_NAME VARCHAR(50) CCSID 937 DEFAULT NULL ,
EMAIL VARCHAR(100) CCSID 937 DEFAULT NULL ,
PHONE_NUMBER FOR COLUMN PHONE00001 VARCHAR(20) CCSID 937 DEFAULT NULL ,
CONSTRAINT DDSCINFO.Q_DDSCINFO_CUSTOMERS_CUSTO00001_00001 PRIMARY KEY(
CUSTOMER_ID ) )

RCDFMT CUSTOMERS  ;
