CREATE TABLE CLOB_TEST
      (COLUMN_A CHAR(10) NOT NULL             ,
       COLUMN_B CLOB(2M) NOT NULL WITH DEFAULT)
 ;
CREATE UNIQUE INDEX INDEX_TEST
       ON           CLOB_TEST
      (COLUMN_A)
 ;
ALTER TABLE CLOB_TEST
  ADD PRIMARY KEY
      (COLUMN_A)
 ;

INSERT INTO CLOB_TEST VALUES ('00', 'TEST00');
INSERT INTO CLOB_TEST VALUES ('01', 'TEST01');
INSERT INTO CLOB_TEST VALUES ('02', 'TEST02');
INSERT INTO CLOB_TEST VALUES ('03', 'TEST03');
INSERT INTO CLOB_TEST VALUES ('04', 'TEST04');
INSERT INTO CLOB_TEST VALUES ('05', 'TEST05');
INSERT INTO CLOB_TEST VALUES ('06', 'TEST06');
INSERT INTO CLOB_TEST VALUES ('07', 'TEST07');
INSERT INTO CLOB_TEST VALUES ('08', 'TEST08');
INSERT INTO CLOB_TEST VALUES ('09', 'TEST09');
INSERT INTO CLOB_TEST VALUES ('10', 'TEST10');
INSERT INTO CLOB_TEST VALUES ('11', 'TEST11');
INSERT INTO CLOB_TEST VALUES ('12', 'TEST12');
INSERT INTO CLOB_TEST VALUES ('13', 'TEST13');
INSERT INTO CLOB_TEST VALUES ('14', 'TEST14');
INSERT INTO CLOB_TEST VALUES ('15', 'TEST15');
INSERT INTO CLOB_TEST VALUES ('16', 'TEST16');
INSERT INTO CLOB_TEST VALUES ('17', 'TEST17');
INSERT INTO CLOB_TEST VALUES ('18', 'TEST18');
INSERT INTO CLOB_TEST VALUES ('19', 'TEST19'); 