SELECT JOURNAL_RECEIVER_LIBRARY,
       JOURNAL_RECEIVER_NAME,
       NUMBER_OF_JOURNAL_ENTRIES,
       SIZE/1024 AS SIZE_MB,
       TIMESTAMPDIFF(4, CHAR(TIMESTAMP(DETACH_TIMESTAMP, 0) - TIMESTAMP(ATTACH_TIMESTAMP, 0))) AS JOURNAL_EXIST_HOURS,
       SIZE / TIMESTAMPDIFF(4, CHAR(TIMESTAMP(DETACH_TIMESTAMP, 0) - TIMESTAMP(ATTACH_TIMESTAMP, 0))) / 1024
           AS JOURNAL_GROWTH_PER_HOUR_MB
    FROM QSYS2.JOURNAL_RECEIVER_INFO
    WHERE DETACH_TIMESTAMP IS NOT NULL
          AND ATTACH_TIMESTAMP IS NOT NULL
          AND JOURNAL_RECEIVER_LIBRARY = 'QGPL'
    ORDER BY JOURNAL_GROWTH_PER_HOUR_MB DESC;