--- 使ILEVEL具有兩個欄位(IVERSION, IRELEASE)

WITH ILEVEL (IVERSION, IRELEASE) AS (
        SELECT OS_VERSION,
               OS_RELEASE
            FROM SYSIBMADM.ENV_SYS_INFO
    )
    SELECT P.*
        FROM ILEVEL,
             SYSTOOLS.GROUP_PTF_CURRENCY P
        WHERE PTF_GROUP_RELEASE = 'R' CONCAT IVERSION CONCAT IRELEASE CONCAT '0'
        ORDER BY PTF_GROUP_LEVEL_AVAILABLE - PTF_GROUP_LEVEL_INSTALLED DESC;

SELECT Z.OS_RELEASE,
       Z.OS_VERSION,
       PTF_GROUP_RELEASE,
       PTF_GROUP_LEVEL_AVAILABLE,
       PTF_GROUP_LEVEL_INSTALLED
    FROM SYSTOOLS.GROUP_PTF_CURRENCY,
         SYSIBMADM.ENV_SYS_INFO Z;